// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: m5core2

#include "ui.h"
#include "../services/mqtt_service.h"
#include <M5Unified.h>

void button2_on(lv_event_t * e)
{
	// Your code here
    client.publish("khoitruong9802/feeds/nutnhan2", "1");
}

void button2_off(lv_event_t * e)
{
	// Your code 
    client.publish("khoitruong9802/feeds/nutnhan2", "0");
}

void button1_on(lv_event_t * e)
{
	// Your code here
    client.publish("khoitruong9802/feeds/nutnhan1", "1");
}

void button1_off(lv_event_t * e)
{
	// Your code here
    client.publish("khoitruong9802/feeds/nutnhan1", "0");
}

void change_brightness(lv_event_t * e)
{
	// Your code here
    lv_obj_t * slider = lv_event_get_target(e);
    uint8_t brightness = (int)lv_slider_get_value(slider);
    M5.Lcd.setBrightness(brightness);
}
